# Form implementation generated from reading ui file 'log.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDisplay(object):
    def setupUi(self, LoginDisplay):
        LoginDisplay.setObjectName("LoginDisplay")
        LoginDisplay.resize(400, 800)
        LoginDisplay.setMinimumSize(QtCore.QSize(400, 800))
        LoginDisplay.setMaximumSize(QtCore.QSize(400, 800))
        self.centralwidget = QtWidgets.QWidget(parent=LoginDisplay)
        self.centralwidget.setObjectName("centralwidget")
        self.DisplayLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.DisplayLabel.setGeometry(QtCore.QRect(50, 20, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DisplayLabel.setFont(font)
        self.DisplayLabel.setObjectName("DisplayLabel")
        self.EmailLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.EmailLabel.setGeometry(QtCore.QRect(20, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EmailLabel.setFont(font)
        self.EmailLabel.setObjectName("EmailLabel")
        self.PasswordLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.PasswordLabel.setGeometry(QtCore.QRect(20, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.usernameinput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.usernameinput.setGeometry(QtCore.QRect(120, 90, 211, 20))
        self.usernameinput.setObjectName("usernameinput")
        self.pwinput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pwinput.setGeometry(QtCore.QRect(120, 140, 211, 20))
        self.pwinput.setObjectName("pwinput")
        self.ForgotPW = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ForgotPW.setGeometry(QtCore.QRect(30, 200, 141, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ForgotPW.setFont(font)
        self.ForgotPW.setObjectName("ForgotPW")
        self.RegisterButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RegisterButton.setGeometry(QtCore.QRect(210, 200, 141, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RegisterButton.setFont(font)
        self.RegisterButton.setObjectName("RegisterButton")
        self.SubmitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(120, 260, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SubmitButton.setFont(font)
        self.SubmitButton.setObjectName("SubmitButton")
        LoginDisplay.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LoginDisplay)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        LoginDisplay.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LoginDisplay)
        self.statusbar.setObjectName("statusbar")
        LoginDisplay.setStatusBar(self.statusbar)

        self.retranslateUi(LoginDisplay)
        QtCore.QMetaObject.connectSlotsByName(LoginDisplay)

    def retranslateUi(self, LoginDisplay):
        _translate = QtCore.QCoreApplication.translate
        LoginDisplay.setWindowTitle(_translate("LoginDisplay", "Login"))
        self.DisplayLabel.setText(_translate("LoginDisplay", "Please enter your account information:"))
        self.EmailLabel.setText(_translate("LoginDisplay", "Email:"))
        self.PasswordLabel.setText(_translate("LoginDisplay", "Password:"))
        self.ForgotPW.setText(_translate("LoginDisplay", "Forgot password?"))
        self.RegisterButton.setText(_translate("LoginDisplay", "Register"))
        self.SubmitButton.setText(_translate("LoginDisplay", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDisplay = QtWidgets.QMainWindow()
    ui = Ui_LoginDisplay()
    ui.setupUi(LoginDisplay)
    LoginDisplay.show()
    sys.exit(app.exec())
