# Form implementation generated from reading ui file 'dep.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DepWindow(object):
    def setupUi(self, DepWindow):
        DepWindow.setObjectName("DepWindow")
        DepWindow.resize(400, 800)
        DepWindow.setMinimumSize(QtCore.QSize(400, 800))
        DepWindow.setMaximumSize(QtCore.QSize(400, 800))
        self.centralwidget = QtWidgets.QWidget(parent=DepWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DepLabel_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.DepLabel_2.setGeometry(QtCore.QRect(160, 20, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DepLabel_2.setFont(font)
        self.DepLabel_2.setObjectName("DepLabel_2")
        self.DepAmountLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.DepAmountLabel.setGeometry(QtCore.QRect(10, 90, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DepAmountLabel.setFont(font)
        self.DepAmountLabel.setObjectName("DepAmountLabel")
        self.DepLabel = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.DepLabel.setGeometry(QtCore.QRect(210, 100, 181, 20))
        self.DepLabel.setObjectName("DepLabel")
        self.DepButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DepButton.setGeometry(QtCore.QRect(40, 270, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DepButton.setFont(font)
        self.DepButton.setObjectName("DepButton")
        self.DepInput2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.DepInput2.setGeometry(QtCore.QRect(210, 190, 181, 20))
        self.DepInput2.setObjectName("DepInput2")
        self.ReLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.ReLabel.setGeometry(QtCore.QRect(10, 180, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ReLabel.setFont(font)
        self.ReLabel.setObjectName("ReLabel")
        self.BackButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(220, 270, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")
        DepWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=DepWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        DepWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=DepWindow)
        self.statusbar.setObjectName("statusbar")
        DepWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DepWindow)
        QtCore.QMetaObject.connectSlotsByName(DepWindow)

    def retranslateUi(self, DepWindow):
        _translate = QtCore.QCoreApplication.translate
        DepWindow.setWindowTitle(_translate("DepWindow", "Deposit"))
        self.DepLabel_2.setText(_translate("DepWindow", "Deposit"))
        self.DepAmountLabel.setText(_translate("DepWindow", "Amount to deposit:"))
        self.DepButton.setText(_translate("DepWindow", "Deposit"))
        self.ReLabel.setText(_translate("DepWindow", "Re-enter Deposit:"))
        self.BackButton.setText(_translate("DepWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DepWindow = QtWidgets.QMainWindow()
    ui = Ui_DepWindow()
    ui.setupUi(DepWindow)
    DepWindow.show()
    sys.exit(app.exec())
