# Form implementation generated from reading ui file 'wit.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Withdraw(object):
    def setupUi(self, Withdraw):
        Withdraw.setObjectName("Withdraw")
        Withdraw.resize(400, 800)
        Withdraw.setMinimumSize(QtCore.QSize(400, 800))
        Withdraw.setMaximumSize(QtCore.QSize(400, 800))
        self.centralwidget = QtWidgets.QWidget(parent=Withdraw)
        self.centralwidget.setObjectName("centralwidget")
        self.WitLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.WitLabel.setGeometry(QtCore.QRect(150, 30, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WitLabel.setFont(font)
        self.WitLabel.setObjectName("WitLabel")
        self.WitAmountLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.WitAmountLabel.setGeometry(QtCore.QRect(10, 90, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WitAmountLabel.setFont(font)
        self.WitAmountLabel.setObjectName("WitAmountLabel")
        self.ReLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.ReLabel.setGeometry(QtCore.QRect(10, 180, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ReLabel.setFont(font)
        self.ReLabel.setObjectName("ReLabel")
        self.WitLabel_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.WitLabel_2.setGeometry(QtCore.QRect(200, 100, 181, 20))
        self.WitLabel_2.setObjectName("WitLabel_2")
        self.WitInput2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.WitInput2.setGeometry(QtCore.QRect(200, 190, 181, 20))
        self.WitInput2.setObjectName("WitInput2")
        self.BackButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BackButton_2.setGeometry(QtCore.QRect(220, 290, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BackButton_2.setFont(font)
        self.BackButton_2.setObjectName("BackButton_2")
        self.WitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.WitButton.setGeometry(QtCore.QRect(40, 290, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WitButton.setFont(font)
        self.WitButton.setObjectName("WitButton")
        Withdraw.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Withdraw)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        Withdraw.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Withdraw)
        self.statusbar.setObjectName("statusbar")
        Withdraw.setStatusBar(self.statusbar)

        self.retranslateUi(Withdraw)
        QtCore.QMetaObject.connectSlotsByName(Withdraw)

    def retranslateUi(self, Withdraw):
        _translate = QtCore.QCoreApplication.translate
        Withdraw.setWindowTitle(_translate("Withdraw", "Withdraw"))
        self.WitLabel.setText(_translate("Withdraw", "Withdraw"))
        self.WitAmountLabel.setText(_translate("Withdraw", "Amount to withdraw:"))
        self.ReLabel.setText(_translate("Withdraw", "Re-enter Withdraw:"))
        self.BackButton_2.setText(_translate("Withdraw", "Back"))
        self.WitButton.setText(_translate("Withdraw", "Withdraw"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Withdraw = QtWidgets.QMainWindow()
    ui = Ui_Withdraw()
    ui.setupUi(Withdraw)
    Withdraw.show()
    sys.exit(app.exec())
